### ISSUE TITLE
Phish duration is in ms, archive in seconds, panic has none

### ISSUE THREAD

**Issue by switz** [RelistenNet/RelistenApi#4]

**Comment by switz** [comment]
For panic, may be able to just request the first few bytes of the file to get the ID3 tags (only for the first time downloading). http://stackoverflow.com/questions/26889317/extract-id3-tags-of-a-mp3-url-with-partial-download-using-python

**Comment by alecgorge** [comment]
@switz for panic, do we *have* to have the duration for Sonos? One of the feature flags are if the tracks have a duration and I'm planning on adding more artists where time data won't be reliable

**Comment by switz** [comment]
We don't have to, but it seems trivial to support. Maybe for v2?

**Comment by alecgorge** [comment]
Splitting Panic into issue #13
